### ISSUE TITLE
transcription of other formats then mp3 does not work (mp4, wav, m4a)

### ISSUE THREAD

**Issue by the-silversurver** [ahmetoner/whisper-asr-webservice#111]
Hi, I am running an instance of web-whisper-plus  from this repository https://codeberg.org/pluja/web-whisper-plus.
This project uses Whisper ASR Webservice and it seems to be the component that causes the problem.

In during the transcription attempt of other formats then mp3  I find the following log entries then the problem occurs: 

```
/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
whisper-asr             |   warnings.warn("FP16 is not supported on CPU; using FP32 instead")
whisper-asr             | [2023-06-04 15:28:21 +0000] [7] [ERROR] Exception in ASGI application
whisper-asr             | Traceback (most recent call last):
whisper-backend         | 3:28PM ERR Invalid status
whisper-backend         | 3:28PM ERR Error processing job error="invalid status"
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
whisper-asr             |     result = await app(  # type: ignore[func-returns-value]
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
whisper-asr             |     return await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
whisper-asr             |     await super().__call__(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
whisper-asr             |     await self.middleware_stack(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
whisper-asr             |     raise exc
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
whisper-asr             |     await self.app(scope, receive, _send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
whisper-asr             |     raise exc
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
whisper-asr             |     await self.app(scope, receive, sender)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
whisper-asr             |     raise e
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
whisper-asr             |     await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
whisper-asr             |     await route.handle(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
whisper-asr             |     await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
whisper-asr             |     response = await func(request)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
whisper-asr             |     raw_response = await run_endpoint_function(
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
whisper-asr             |     return await run_in_threadpool(dependant.call, **values)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
whisper-asr             |     return await anyio.to_thread.run_sync(func, *args)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
whisper-asr             |     return await get_asynclib().run_sync_in_worker_thread(
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
whisper-asr             |     return await future
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
whisper-asr             |     result = context.run(func, *args)
whisper-asr             |   File "/app/app/webservice.py", line 69, in asr
whisper-asr             |     result = transcribe(load_audio(audio_file.file, encode), task, language, initial_prompt, word_timestamps, output)
whisper-asr             |   File "/app/app/openai_whisper/core.py", line 31, in transcribe
whisper-asr             |     result = model.transcribe(audio, **options_dict)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
whisper-asr             |     mel = log_mel_spectrogram(audio)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram
whisper-asr             |     stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/torch/functional.py", line 630, in stft
whisper-asr             |     input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
whisper-asr             | RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]
```
 
Recording from a connected mic fails with these log entries:
```
 3:54PM ERR Error processing job error="invalid status"
whisper-asr             | [2023-06-04 15:54:08 +0000] [7] [ERROR] Exception in ASGI application
whisper-asr             | Traceback (most recent call last):
whisper-asr             |   File "/app/app/webservice.py", line 107, in load_audio
whisper-asr             |     ffmpeg.input("pipe:", threads=0)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
whisper-asr             |     raise Error('ffmpeg', out, err)
whisper-asr             | ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
whisper-asr             | 
whisper-asr             | The above exception was the direct cause of the following exception:
whisper-asr             | 
whisper-asr             | Traceback (most recent call last):
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
whisper-asr             |     result = await app(  # type: ignore[func-returns-value]
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
whisper-asr             |     return await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
whisper-asr             |     await super().__call__(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
whisper-asr             |     await self.middleware_stack(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
whisper-asr             |     raise exc
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
whisper-asr             |     await self.app(scope, receive, _send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
whisper-asr             |     raise exc
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
whisper-asr             |     await self.app(scope, receive, sender)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
whisper-asr             |     raise e
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
whisper-asr             |     await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
whisper-asr             |     await route.handle(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
whisper-asr             |     await self.app(scope, receive, send)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
whisper-asr             |     response = await func(request)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
whisper-asr             |     raw_response = await run_endpoint_function(
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
whisper-asr             |     return await run_in_threadpool(dependant.call, **values)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
whisper-asr             |     return await anyio.to_thread.run_sync(func, *args)
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
whisper-asr             |     return await get_asynclib().run_sync_in_worker_thread(
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
whisper-asr             |     return await future
whisper-asr             |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
whisper-asr             |     result = context.run(func, *args)
whisper-asr             |   File "/app/app/webservice.py", line 69, in asr
whisper-asr             |     result = transcribe(load_audio(audio_file.file, encode), task, language, initial_prompt, word_timestamps, output)
whisper-asr             |   File "/app/app/webservice.py", line 112, in load_audio
whisper-asr             |     raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
whisper-asr             | RuntimeError: Failed to load audio: ffmpeg version 4.3.6-0+deb11u1 Copyright (c) 2000-2023 the FFmpeg developers
whisper-asr             |   built with gcc 10 (Debian 10.2.1-6)
whisper-asr             |   configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
whisper-asr             |   libavutil      56. 51.100 / 56. 51.100
whisper-asr             |   libavcodec     58. 91.100 / 58. 91.100
whisper-asr             |   libavformat    58. 45.100 / 58. 45.100
whisper-asr             |   libavdevice    58. 10.100 / 58. 10.100
whisper-asr             |   libavfilter     7. 85.100 /  7. 85.100
whisper-asr             |   libavresample   4.  0.  0 /  4.  0.  0
whisper-asr             |   libswscale      5.  7.100 /  5.  7.100
whisper-asr             |   libswresample   3.  7.100 /  3.  7.100
whisper-asr             |   libpostproc    55.  7.100 / 55.  7.100
whisper-asr             | pipe:: Invalid data found when processing input
```
 
This is how my docker-compose.yaml looks like:

```
version: "3.9"

services:
whisper-asr:
container_name: whisper-asr
image: onerahmet/openai-whisper-asr-webservice:v1.1.1
env_file:
- .env
environment:
ASR_MODEL: ${WHISPER_MODEL}
volumes:
- cache-whisper:/root/.cache/whisper
restart: unless-stopped
expose:
- 9000

translate:
container_name: whisper-libretranslate
image: libretranslate/libretranslate:latest
restart: unless-stopped
env_file:
- .env
environment:
LT_DISABLE_WEB_UI: True
LT_DEBUG: True
expose:
- 5000

backend:
container_name: whisper-backend
image: pluja/web-whisper-backend:latest
env_file:
- .env
environment:
UPLOAD_DIR: ${UPLOAD_DIR-/tmp}
ASR_ENDPOINT: whisper-asr:9000
LT_ENDPOINT: ${LT_ENDPOINT-translate:5000}
volumes:
- ./db_data:/app/db
restart: unless-stopped
expose:
- 3000

webui:
container_name: whisper-webui
image: pluja/web-whisper-frontend:latest
env_file:
- .env
restart: unless-stopped
expose:
- 5173

whisper-proxy:
container_name: whisper-proxy
image: caddy:2-alpine
restart: unless-stopped
ports:
- 8899:80
volumes:
- ./Caddyfile:/etc/caddy/Caddyfile

volumes:
cache-whisper:

```

Please let me know if I can do anything to support the debugging.

**Comment by thet0ast3r** [comment]
do the mp4 container files have --movflags faststart? 

i found that it doesn't work when im not using those flags when muxing. 
See #97 :)

**Comment by the-silversurver** [comment]
Thanks! 
That was a good hint. After recreating the file with this flag, the transcoding starts. 
Would be fantastic, if this would not be necessary in a future version

**Comment by dahifi** [comment]
Just wanted to bump this. I had to configure OBS to use MKV file because the MP4s wont transcribe. 

Anyone running into this problem can fix files on their end with this snippet: 
```
for file in *.mp4; do
    ffmpeg -i "$file" -c copy -movflags faststart "temp_$file"
    mv "temp_$file" "$file"
done
```
As far as fixing the current endpoint, I believe we can modify the load_audio function in [webservice.py](https://github.com/ahmetoner/whisper-asr-webservice/blob/50aefcfae36092f7d3dd1343204846e3b810bd19/app/webservice.py)
```
def load_audio(file: BinaryIO, encode=True, sr: int = SAMPLE_RATE):
    """
    ... (existing docstring)
    """
    if encode:
        try:
            # Add the `-movflags faststart` flag to ensure MOOV atom is at the beginning
            out, _ = (
                ffmpeg.input("pipe:", threads=0, movflags="faststart")
                .output("-", format="s16le", acodec="pcm_s16le", ac=1, ar=sr)
                .run(cmd="ffmpeg", capture_stdout=True, capture_stderr=True, input=file.read())
            )
        except ffmpeg.Error as e:
            raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
    else:
        out = file.read()

    return np.frombuffer(out, np.int16).flatten().astype(np.float32) / 32768.0
```
I probably wont get to testing this soon as I don't have dev setup currently and would rather get diarization working first.

**Comment by dahifi** [comment]
GPT and me just wrote this bash script to check if MP4 files have the moov atom before the mdat flag, and re-encodes it if not. I'm adding this as an automator script on my OBS output directory since I can't figure out how to do in OBS directly. 
```
#!/usr/bin/env bash

for file in "$@"
do
    if [[ "$file" == *.mp4 ]]; then
        first_atom=$(ffmpeg -v trace -i "$file" 2>&1 | grep -m 1 -o -e "type:'mdat'" -e "type:'moov'")
        
        if [[ $first_atom == "type:'moov'" ]]; then
            echo "The file $file already has the faststart flag. Skipping."
        else
            echo "Adding faststart to $file."
            dir=$(dirname "$file")
            filename=$(basename "$file")
            ffmpeg -i "$file" -c copy -movflags faststart "$dir/temp_$filename"
            mv "$dir/temp_$filename" "$file"
        fi
    fi
done
```

**Comment by ayancey** [comment]
We stream the input directly into ffmpeg if the encode flag is set, so we are limited by whatever ffmpeg is capable of. If you encounter this problem, consider re-encoding the audio stream on the client side before sending it to the ASR.
