### ISSUE TITLE
Unable to start 8 workers with faster_whisper CPU mode

### ISSUE THREAD

**Issue by fondoger** [ahmetoner/whisper-asr-webservice#122]
For a single worker, the docker works perfectly. However, when specifying 8 workers, it begins to fail.

Command to reproduce issue:

```bash
# Starting 8 workers
docker run --rm -it -p 9000:9000 -e ASR_MODEL=base --entrypoint gunicorn -e ASR_ENGINE=faster_whisper onerahmet/openai-whisper-asr-webservice:latest  --bind 0.0.0.0:9000 --workers 8 --timeout 0 app.webservice:app -k uvicorn.workers.UvicornWorker
```

Log:
```log
docker run --rm -it -p 9000:9000 -e ASR_MODEL=base --entrypoint gunicorn -e ASR_ENGINE=faster_whisper onerahmet/openai-whisper-asr-webservice:latest  --bind 0.0.0.0:9000 --workers 2 --timeout 0 app.webservice:app -k uvicorn.workers.UvicornWorker
[2023-07-25 04:21:29 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-07-25 04:21:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
[2023-07-25 04:21:29 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-07-25 04:21:29 +0000] [7] [INFO] Booting worker with pid: 7
[2023-07-25 04:21:29 +0000] [27] [INFO] Booting worker with pid: 27
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.98k/1.98k [00:00<00:00, 1.81MB/s]
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 290M/290M [00:06<00:00, 43.2MB/s]
Downloading (…)neration_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.51k/3.51k [00:00<00:00, 3.26MB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 840/840 [00:00<00:00, 670kB/s]
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 1.12MB/s]
Downloading (…)/main/tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:01<00:00, 1.92MB/s]
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 494k/494k [00:00<00:00, 1.06MB/s]
Downloading (…)main/normalizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.7k/52.7k [00:00<00:00, 714kB/s]
Downloading (…)in/added_tokens.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.08k/2.08k [00:00<00:00, 1.80MB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.08k/2.08k [00:00<00:00, 1.51MB/s]
[2023-07-25 04:21:53 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/webservice.py", line 16, in <module>
    from .faster_whisper.core import transcribe, language_detection
  File "/app/app/faster_whisper/core.py", line 19, in <module>
    model = WhisperModel(model_path, device="cpu", compute_type="int8")
  File "/app/.venv/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 101, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: File model.bin is incomplete: failed to read a buffer of size 2097152 at position 139478463
[2023-07-25 04:21:53 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-07-25 04:21:53 +0000] [1] [WARNING] Worker with pid 27 was terminated due to signal 15
[2023-07-25 04:21:54 +0000] [1] [INFO] Shutting down: Master
[2023-07-25 04:21:54 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by fondoger** [comment]
Update: 

By mounting the cache directory (/root/.cache/whisper) to an persistent storage solves this issue.

This can be documented in README.md if possible.
