### ISSUE TITLE
TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'repetition_penalty'

### ISSUE THREAD

**Issue by andrealorenzon** [ahmetoner/whisper-asr-webservice#130]
Got the error in subject since the last week during container build while sending an audio to webservice endpoint.

Full stacktrace:

```bash
whisper           | [2023-09-18 08:12:32 +0000] [8] [ERROR] Exception in ASGI application
whisper           | Traceback (most recent call last):
whisper           |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
whisper           |     result = await app(  # type: ignore[func-returns-value]
whisper           |   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
whisper           |     return await self.app(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
whisper           |     await super().__call__(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
whisper           |     await self.middleware_stack(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
whisper           |     raise exc
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
whisper           |     await self.app(scope, receive, _send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
whisper           |     raise exc
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
whisper           |     await self.app(scope, receive, sender)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
whisper           |     raise e
whisper           |   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
whisper           |     await self.app(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
whisper           |     await route.handle(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
whisper           |     await self.app(scope, receive, send)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
whisper           |     response = await func(request)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
whisper           |     raw_response = await run_endpoint_function(
whisper           |   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
whisper           |     return await run_in_threadpool(dependant.call, **values)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
whisper           |     return await anyio.to_thread.run_sync(func, *args)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
whisper           |     return await get_asynclib().run_sync_in_worker_thread(
whisper           |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
whisper           |     return await future
whisper           |   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
whisper           |     result = context.run(func, *args)
whisper           |   File "/app/app/webservice.py", line 188, in whisperx_call
whisper           |     model = whisperx.load_model(**model_params)
whisper           |   File "/app/.venv/lib/python3.10/site-packages/whisperx/asr.py", line 92, in load_model
whisper           |     default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
whisper           | TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'repetition_penalty'
```

Container pip freeze:

```bash
.venv) root@647e24e77523:/app# pip freeze
aiohttp==3.8.5
aiosignal==1.3.1
alembic==1.12.0
antlr4-python3-runtime==4.9.3
anyio==3.6.2
arrow==1.2.3
asteroid-filterbanks==0.4.0
async-timeout==4.0.3
attrs==23.1.0
audioread==3.0.0
av==10.0.0
backoff==2.2.1
beautifulsoup4==4.12.2
blessed==1.20.0
build==0.10.0
CacheControl==0.12.14
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
cleo==2.0.1
click==8.1.3
cmaes==0.10.0
cmake==3.27.5
colorama==0.4.6
coloredlogs==15.0.1
colorlog==6.7.0
contourpy==1.1.1
crashtest==0.4.1
croniter==1.4.1
cryptography==41.0.3
ctranslate2==3.12.0
cycler==0.11.0
dateutils==0.6.12
decorator==5.1.1
deepdiff==6.5.0
distlib==0.3.7
docopt==0.6.2
dulwich==0.21.5
einops==0.6.1
fastapi==0.95.1
faster-whisper==0.4.1
ffmpeg-python==0.2.0
filelock==3.11.0
flatbuffers==23.3.3
fonttools==4.42.1
frozenlist==1.4.0
fsspec==2023.9.1
future==0.18.3
greenlet==2.0.2
gunicorn==20.1.0
h11==0.14.0
html5lib==1.1
httptools==0.5.0
huggingface-hub==0.13.4
humanfriendly==10.0
HyperPyYAML==1.2.1
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
inquirer==3.1.3
installer==0.6.0
itsdangerous==2.1.2
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
julius==0.2.7
keyring==23.13.1
kiwisolver==1.4.5
lazy_loader==0.3
librosa==0.10.1
lightning==2.0.9
lightning-cloud==0.5.38
lightning-utilities==0.9.0
lit==16.0.6
llvmlite==0.39.1
lockfile==0.12.2
Mako==1.2.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.0
mdurl==0.1.2
more-itertools==9.1.0
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
networkx==3.1
nltk==3.8.1
numba==0.56.4
numpy==1.23.5
omegaconf==2.3.0
onnxruntime==1.14.1
openai-whisper==20230124
optuna==3.3.0
ordered-set==4.1.0
packaging==23.1
pandas==2.1.0
pexpect==4.8.0
Pillow==10.0.1
pkginfo==1.9.6
platformdirs==2.6.2
pluggy==1.0.0
poetry==1.4.0
poetry-core==1.5.1
poetry-plugin-export==1.3.1
pooch==1.7.0
primePy==1.3
protobuf==4.22.3
psutil==5.9.5
ptyprocess==0.7.0
py==1.11.0
pyannote.audio @ git+https://github.com/pyannote/pyannote-audio@11b56a137a578db9335efc00298f6ec1932e6317
pyannote.core==5.0.0
pyannote.database==5.0.1
pyannote.metrics==3.2.1
pyannote.pipeline==2.3
pycparser==2.21
pydantic==1.10.7
Pygments==2.16.1
PyJWT==2.8.0
pyparsing==3.1.1
pyproject_hooks==1.0.0
pytest==6.2.5
python-dateutil==2.8.2
python-dotenv==1.0.0
python-editor==1.0.4
python-multipart==0.0.5
pytorch-lightning==2.0.9
pytorch-metric-learning==2.3.0
pytz==2023.3.post1
PyYAML==6.0
rapidfuzz==2.15.1
readchar==4.0.5
referencing==0.30.2
regex==2023.3.23
requests==2.28.2
requests-toolbelt==0.10.1
rich==13.5.3
rpds-py==0.10.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
scikit-learn==1.3.0
scipy==1.11.2
SecretStorage==3.3.3
semver==3.0.1
sentencepiece==0.1.99
shellingham==1.5.3
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.6
speechbrain==0.5.15
SQLAlchemy==2.0.20
starlette==0.26.1
starsessions==1.3.0
sympy==1.11.1
tabulate==0.9.0
tensorboardX==2.6.2.2
threadpoolctl==3.2.0
tokenizers==0.13.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1+cu117
torch-audiomentations==0.11.0
torch-pitch-shift==1.2.4
torchaudio==2.0.2
torchmetrics==1.1.2
tqdm==4.65.0
traitlets==5.10.0
transformers==4.28.1
triton==2.0.0
trove-classifiers==2023.8.7
typer==0.9.0
typing_extensions==4.5.0
tzdata==2023.3
Unidecode==1.3.6
urllib3==1.26.15
uvicorn==0.18.3
uvloop==0.17.0
virtualenv==20.21.1
watchfiles==0.19.0
wcwidth==0.2.6
webencodings==0.5.1
websocket-client==1.6.3
websockets==11.0.1
# Editable install with no version control (whisper-asr-webservice==1.1.1)
-e /app
whisperx @ git+https://github.com/m-bain/whisperx.git@b1a98b78c9152ace9f9801593b5fa0c7d5d96b0f
yarl==1.9.2
zipp==3.16.2
```

**Comment by ayancey** [comment]
Can you try the new 1.2 release and let me know if this is still happening?

**Comment by andrealorenzon** [comment]
sorry. forgot to reply. That fixed the issue, thank you.
