### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 28-33: ordinal not in range(256)

### ISSUE THREAD

**Issue by leoterry-ulrica** [ahmetoner/whisper-asr-webservice#178]
```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/app/webservice.py", line 78, in asr
    return StreamingResponse(
  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 246, in __init__
    self.init_headers(headers)
  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in init_headers
    raw_headers = [
  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 74, in <listcomp>
    (k.lower().encode("latin-1"), v.encode("latin-1"))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 28-33: ordinal not in range(256)
```

**Comment by hcxss** [comment]
Hey, how did you solve the problem?

**Comment by leoterry-ulrica** [comment]
> Hey, how did you solve the problem?

Changed the data format to mp3
