### ISSUE TITLE
Error: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Sam7** [ahmetoner/whisper-asr-webservice#204]
I'm getting this error after just running `docker run -d --gpus all -p 9000:9000 -e ASR_MODEL=base -e ASR_ENGINE=openai_whisper onerahmet/openai-whisper-asr-webservice:latest-gpu`
`CERTIFICATE_VERIFY_FAILED`

Anyone else having the same issue?

```
2024-03-22 12:03:42 
2024-03-22 12:03:42 ==========
2024-03-22 12:03:42 == CUDA ==
2024-03-22 12:03:42 ==========
2024-03-22 12:03:42 
2024-03-22 12:03:42 CUDA Version 11.8.0
2024-03-22 12:03:42 
2024-03-22 12:03:42 Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024-03-22 12:03:42 
2024-03-22 12:03:42 This container image and its contents are governed by the NVIDIA Deep Learning Container License.
2024-03-22 12:03:42 By pulling and using the container, you accept the terms and conditions of this license:
2024-03-22 12:03:42 https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
2024-03-22 12:03:42 
2024-03-22 12:03:42 A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
2024-03-22 12:03:42 
2024-03-22 12:03:43 [2024-03-22 01:03:43 +0000] [27] [INFO] Starting gunicorn 21.2.0
2024-03-22 12:03:43 [2024-03-22 01:03:43 +0000] [27] [INFO] Listening at: http://0.0.0.0:9000 (27)
2024-03-22 12:03:43 [2024-03-22 01:03:43 +0000] [27] [INFO] Using worker: uvicorn.workers.UvicornWorker
2024-03-22 12:03:43 [2024-03-22 01:03:43 +0000] [28] [INFO] Booting worker with pid: 28
2024-03-22 12:03:46 [2024-03-22 01:03:46 +0000] [28] [ERROR] Exception in worker process
2024-03-22 12:03:46 Traceback (most recent call last):
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
2024-03-22 12:03:46     h.request(req.get_method(), req.selector, req.data, headers,
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 1283, in request
2024-03-22 12:03:46     self._send_request(method, url, body, headers, encode_chunked)
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
2024-03-22 12:03:46     self.endheaders(body, encode_chunked=encode_chunked)
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
2024-03-22 12:03:46     self._send_output(message_body, encode_chunked=encode_chunked)
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
2024-03-22 12:03:46     self.send(msg)
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 976, in send
2024-03-22 12:03:46     self.connect()
2024-03-22 12:03:46   File "/usr/lib/python3.10/http/client.py", line 1455, in connect
2024-03-22 12:03:46     self.sock = self._context.wrap_socket(self.sock,
2024-03-22 12:03:46   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
2024-03-22 12:03:46     return self.sslsocket_class._create(
2024-03-22 12:03:46   File "/usr/lib/python3.10/ssl.py", line 1100, in _create
2024-03-22 12:03:46     self.do_handshake()
2024-03-22 12:03:46   File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
2024-03-22 12:03:46     self._sslobj.do_handshake()
2024-03-22 12:03:46 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)
2024-03-22 12:03:46 
2024-03-22 12:03:46 During handling of the above exception, another exception occurred:
2024-03-22 12:03:46 
2024-03-22 12:03:46 Traceback (most recent call last):
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-03-22 12:03:46     worker.init_process()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2024-03-22 12:03:46     super(UvicornWorker, self).init_process()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-03-22 12:03:46     self.load_wsgi()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-03-22 12:03:46     self.wsgi = self.app.wsgi()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-03-22 12:03:46     self.callable = self.load()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-03-22 12:03:46     return self.load_wsgiapp()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-03-22 12:03:46     return util.import_app(self.app_uri)
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2024-03-22 12:03:46     mod = importlib.import_module(module)
2024-03-22 12:03:46   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-03-22 12:03:46     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-22 12:03:46   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-03-22 12:03:46   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-03-22 12:03:46   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-03-22 12:03:46   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-03-22 12:03:46   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-03-22 12:03:46   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-22 12:03:46   File "/app/app/webservice.py", line 19, in <module>
2024-03-22 12:03:46     from .openai_whisper.core import transcribe, language_detection
2024-03-22 12:03:46   File "/app/app/openai_whisper/core.py", line 14, in <module>
2024-03-22 12:03:46     model = whisper.load_model(model_name, download_root=model_path).cuda()
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 133, in load_model
2024-03-22 12:03:46     checkpoint_file = _download(_MODELS[name], download_root, in_memory)
2024-03-22 12:03:46   File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 69, in _download
2024-03-22 12:03:46     with urllib.request.urlopen(url) as source, open(download_target, "wb") as output:
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
2024-03-22 12:03:46     return opener.open(url, data, timeout)
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
2024-03-22 12:03:46     response = self._open(req, data)
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
2024-03-22 12:03:46     result = self._call_chain(self.handle_open, protocol, protocol +
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
2024-03-22 12:03:46     result = func(*args)
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
2024-03-22 12:03:46     return self.do_open(http.client.HTTPSConnection, req,
2024-03-22 12:03:46   File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
2024-03-22 12:03:46     raise URLError(err)
2024-03-22 12:03:46 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)>
2024-03-22 12:03:46 [2024-03-22 01:03:46 +0000] [28] [INFO] Worker exiting (pid: 28)
2024-03-22 12:03:46 [2024-03-22 01:03:46 +0000] [27] [ERROR] Worker (pid:28) exited with code 3
2024-03-22 12:03:46 [2024-03-22 01:03:46 +0000] [27] [ERROR] Shutting down: Master
2024-03-22 12:03:46 [2024-03-22 01:03:46 +0000] [27] [ERROR] Reason: Worker failed to boot.
```

**Comment by ayancey** [comment]
Corporate proxy?

**Comment by Sam7** [comment]
Good thinking. I think you might be right on that.
Any clue how to get around that?

**Comment by ayancey** [comment]
Sorry not sure. Check your docker networking and the http proxy environment variable
