### ISSUE TITLE
ValueError: Unsupported ASR engine: faster-whisper

### ISSUE THREAD

**Issue by danktankk** [ahmetoner/whisper-asr-webservice#264]
Im getting this error when i try to load this container.   Here are some log files, but they arent very helpful.

```
==========
== CUDA ==
==========
CUDA Version 11.8.0
Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
Traceback (most recent call last):
  File "/app/.venv/bin/whisper-asr-webservice", line 3, in <module>
    from app.webservice import start
  File "/app/app/webservice.py", line 19, in <module>
    asr_model = ASRModelFactory.create_asr_model()
  File "/app/app/factory/asr_model_factory.py", line 15, in create_asr_model
    raise ValueError(f"Unsupported ASR engine: {CONFIG.ASR_ENGINE}")
ValueError: Unsupported ASR engine: faster-whisper
Container stopped
```

If I can get anything else you need, please let me know.  It wont start with either faster-whisper or openai-whisper.

**Comment by ahmetoner** [comment]
There is a typo in your environment variable. Please use `faster_whisper` instead of `faster-whisper`.

**Comment by danktankk** [comment]
> There is a typo in your environment variable. Please use `faster_whisper` instead of `faster-whisper`.

well thats embarrasing, but ill take that over something that cant be fixed for a while anyday!  Thank you for such a fast reply!  Solved!
