### ISSUE TITLE
RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]

### ISSUE THREAD

**Issue by vdsharma** [ahmetoner/whisper-asr-webservice#56]
I am getting the following error while running this on Mac ( Intel)

Run Command: 
 docker run -d -p 9000:9000 -e ASR_MODEL=base onerahmet/openai-whisper-asr-webservice:latest

Console Log:

2022-12-19 19:47:42 +0000] [1] [INFO] Starting gunicorn 20.1.0

[2022-12-19 19:47:42 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)

[2022-12-19 19:47:42 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker

[2022-12-19 19:47:42 +0000] [8] [INFO] Booting worker with pid: 8

 26%|█████████▋                            | 35.4M/139M [00:13<00:29, 3.73MiB/s]

 72%|███████████████████████████▎          | 99.4M/139M [00:24<00:06, 6.57MiB/s]

100%|███████████████████████████████████████| 139M/139M [00:31<00:00, 4.62MiB/s]

[2022-12-19 19:48:16 +0000] [8] [INFO] Started server process [8]

[2022-12-19 19:48:16 +0000] [8] [INFO] Waiting for application startup.

[2022-12-19 19:48:16 +0000] [8] [INFO] Application startup complete.

/app/.venv/lib/python3.9/site-packages/whisper/transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead

  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[2022-12-19 19:50:26 +0000] [8] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 70, in transcribe

    result = run_asr(audio_file.file, task, language)

  File "/app/app/webservice.py", line 117, in run_asr

    result = model.transcribe(audio, **options_dict)

  File "/app/.venv/lib/python3.9/site-packages/whisper/transcribe.py", line 84, in transcribe

    mel = log_mel_spectrogram(audio)

  File "/app/.venv/lib/python3.9/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram

    stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)

  File "/app/.venv/lib/python3.9/site-packages/torch/functional.py", line 630, in stft

    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)

RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]

**Comment by mcutshaw** [comment]
So I don't have a great fix for this atm, but I know its due to ffmpeg not producing any output, leaving the tensor more or less empty.

**Comment by vdsharma** [comment]
Thanks. I changed the file format and it works now.
