### ISSUE TITLE
gunicorn is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by Leafonix** [ahmetoner/whisper-asr-webservice#59]
When I try to run the gunicorn command, I keep getting the error: 

"gunicorn is not recognized as an internal or external command, operable program, or batch file"

All the other command work, just this one is giving me issues.

**Comment by StefanBlamberg** [comment]
For me it worked to run it via poetry
`poetry run gunicorn --bind 0.0.0.0:9001 --workers 1 --timeout 0 app.webservice:app -k uvicorn.workers.UvicornWorker`

**Comment by Leafonix** [comment]
I tried that and it gave me the same error.
  

  

  

  
  
  
  
  
>

**Comment by StefanBlamberg** [comment]
Was the `poetry install` successful for you?
In my case it failed to install some of the dependencies at first because the commited poetry.lock somehow doesn't match the pyproject.toml.
 `Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies.`

I ran `poetry lock` and then reinstalled the dependencies which fixed the issue
I am not a poetry expert though so maybe that's not the proper way to fix this

**Comment by Leafonix** [comment]
I will try that and see how it goes.
  

  

  

  
  
  
  
>

**Comment by Leafonix** [comment]
> Was the `poetry install` successful for you? In my case it failed to install some of the dependencies at first because the commited poetry.lock somehow doesn't match the pyproject.toml. `Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies.`
> 
> I ran `poetry lock` and then reinstalled the dependencies which fixed the issue I am not a poetry expert though so maybe that's not the proper way to fix this

This defintely did something, but I'm still getting the same issue with running gunicorn. My output is below:

>>Traceback (most recent call last):
  File "C:\Users\hanna\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hanna\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanna\AppData\Local\pypoetry\Cache\virtualenvs\whisper-asr-webservice-gntCQkU7-py3.9\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "C:\Users\hanna\AppData\Local\pypoetry\Cache\virtualenvs\whisper-asr-webservice-gntCQkU7-py3.9\lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "C:\Users\hanna\AppData\Local\pypoetry\Cache\virtualenvs\whisper-asr-webservice-gntCQkU7-py3.9\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Users\hanna\AppData\Local\pypoetry\Cache\virtualenvs\whisper-asr-webservice-gntCQkU7-py3.9\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Any help with this would be appreciated

**Comment by StefanBlamberg** [comment]
Might be some Windows issue according to https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl
I am on MacOS though so I didn't encounter this, sorry

**Comment by Leafonix** [comment]
So it looks like Windows doesn't have a `fcnt` module. Does that make this entire extension unusable for Windows users? 
@ahmetoner

**Comment by ahmetoner** [comment]
Hello @Leafonix,

Could you please try following run command?
 `poetry run uvicorn app.webservice:app --port 9000`
