### ISSUE TITLE
Can't run docker 

### ISSUE THREAD

**Issue by DamonGuzman** [ahmetoner/whisper-asr-webservice#73]
2023-02-04 17:35:15 [2023-02-05 01:35:15 +0000] [1] [INFO] Starting gunicorn 20.1.0
2023-02-04 17:35:15 [2023-02-05 01:35:15 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
2023-02-04 17:35:15 [2023-02-05 01:35:15 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-02-04 17:35:15 [2023-02-05 01:35:15 +0000] [8] [INFO] Booting worker with pid: 8
2023-02-04 17:35:26 [2023-02-05 01:35:26 +0000] [8] [ERROR] Exception in worker process
2023-02-04 17:35:26 Traceback (most recent call last):
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
2023-02-04 17:35:26     h.request(req.get_method(), req.selector, req.data, headers,
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
2023-02-04 17:35:26     self._send_request(method, url, body, headers, encode_chunked)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
2023-02-04 17:35:26     self.endheaders(body, encode_chunked=encode_chunked)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
2023-02-04 17:35:26     self._send_output(message_body, encode_chunked=encode_chunked)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
2023-02-04 17:35:26     self.send(msg)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 975, in send
2023-02-04 17:35:26     self.connect()
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 1447, in connect
2023-02-04 17:35:26     super().connect()
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
2023-02-04 17:35:26     self.sock = self._create_connection(
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
2023-02-04 17:35:26     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-02-04 17:35:26     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-02-04 17:35:26 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-02-04 17:35:26 
2023-02-04 17:35:26 During handling of the above exception, another exception occurred:
2023-02-04 17:35:26 
2023-02-04 17:35:26 Traceback (most recent call last):
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-02-04 17:35:26     worker.init_process()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-02-04 17:35:26     super(UvicornWorker, self).init_process()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-02-04 17:35:26     self.load_wsgi()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-02-04 17:35:26     self.wsgi = self.app.wsgi()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-02-04 17:35:26     self.callable = self.load()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-02-04 17:35:26     return self.load_wsgiapp()
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-02-04 17:35:26     return util.import_app(self.app_uri)
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2023-02-04 17:35:26     mod = importlib.import_module(module)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-02-04 17:35:26     return _bootstrap._gcd_import(name[level:], package, level)
2023-02-04 17:35:26   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-02-04 17:35:26   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-02-04 17:35:26   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-02-04 17:35:26   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-02-04 17:35:26   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-02-04 17:35:26   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-02-04 17:35:26   File "/app/app/webservice.py", line 55, in <module>
2023-02-04 17:35:26     model = whisper.load_model(model_name)
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 108, in load_model
2023-02-04 17:35:26     checkpoint_file = _download(_MODELS[name], download_root, in_memory)
2023-02-04 17:35:26   File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 50, in _download
2023-02-04 17:35:26     with urllib.request.urlopen(url) as source, open(download_target, "wb") as output:
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
2023-02-04 17:35:26     return opener.open(url, data, timeout)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
2023-02-04 17:35:26     response = self._open(req, data)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
2023-02-04 17:35:26     result = self._call_chain(self.handle_open, protocol, protocol +
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
2023-02-04 17:35:26     result = func(*args)
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
2023-02-04 17:35:26     return self.do_open(http.client.HTTPSConnection, req,
2023-02-04 17:35:26   File "/usr/local/lib/python3.10/urllib/request.py", line 1351, in do_open
2023-02-04 17:35:26     raise URLError(err)
2023-02-04 17:35:26 urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
2023-02-04 17:35:26 [2023-02-05 01:35:26 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-02-04 17:35:26 [2023-02-05 01:35:26 +0000] [1] [INFO] Shutting down: Master
2023-02-04 17:35:26 [2023-02-05 01:35:26 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by ahmetoner** [comment]
Hello @DamonGuzman,

Could you please share your running environment and container details?

**Comment by clintdavis77** [comment]
So I had this same issue. The issue was I have multiple network cards, one of which did not have internet access. For me the solution was to unplug that network card that did not have internet access and it ran fine. This may only be an issue for the first run since it looks like it downloads the model. @ahmetoner @DamonGuzman

**Comment by ahmetoner** [comment]
@clintdavis77, Thanks for reporting your solution for offline usage.

@DamonGuzman If you want to use whisper completely offline, you should store models ([download links](https://github.com/openai/whisper/blob/0b5dcfdef7ec04250b76e13f1630e32b0935ce76/whisper/__init__.py#L17-L29)) in a local directory and then you should mount this directory to container. Here is an example:

```yml
# via Docker run

docker run -d -p 9000:9000 -e ASR_MODEL=base -v /whisper-models-directory:/root/.cache/whisper onerahmet/openai-whisper-asr-webservice:latest

# in docker-compose.yml
volumes:
    - /whisper-models-directory:/root/.cache/whisper
```
