### ISSUE TITLE
Running dual GPUs. Only one is used.

### ISSUE THREAD

**Issue by rainmanjam** [ahmetoner/whisper-asr-webservice#75]
Processor	13th Gen Intel(R) Core(TM) i9-13900KF   3.00 GHz
Installed RAM	64.0 GB (63.8 GB usable)
System type	64-bit operating system, x64-based processor
GPU : Dual Nvidia Geforce 3090

![image](https://user-images.githubusercontent.com/181322/217744036-8401d5b9-8748-4374-a5a6-602b6fda64ec.png)

```
PS C:\Users\rainm> docker run -it --gpus=all --rm nvidia/cuda:11.4.2-base-ubuntu20.04 nvidia-smi
Thu Feb  9 07:10:31 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8    43W / 420W |  11306MiB / 24576MiB |     15%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
|  0%   48C    P8    38W / 420W |  11306MiB / 24576MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A         7      C   /python3.10                     N/A      |
|    1   N/A  N/A         7      C   /python3.10                     N/A      |
+-----------------------------------------------------------------------------+```

```
2023-02-08 16:13:49 [2023-02-09 00:13:49 +0000] [1] [INFO] Starting gunicorn 20.1.0
2023-02-08 16:13:49 [2023-02-09 00:13:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
2023-02-08 16:13:49 [2023-02-09 00:13:49 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-02-08 16:13:49 [2023-02-09 00:13:49 +0000] [7] [INFO] Booting worker with pid: 7
 14%|��2023-02-09T00:14:09.555821584Z �████▍                                | 41 27%|██████████▏                         2023-02-09T00:14:09.555821584Z   | 789M 39%|██████████████▎                      | 1.11G2023-02-09T00:14:09.555821584Z  49%|��2023-02-09T00:14:09.555821584Z �█████████████████▎                  | 1.4 60%|████████��2023-02-09T00:14:09.555821584Z �█████████████               | 1.7 69%|█████████████████████████▋          2023-02-09T00:14:09.555821584Z  | 2.00G 79%|█████████████████████████████        |2023-02-09T00:14:09.555821584Z  2.26G 87%|███��2023-02-09T00:14:09.555821584Z �████████████████████████████▎    | 2.5 96%|████████████████████████████████2023-02-09T00:14:09.555821584Z ███▍ | 2.75G100%|█████████████████████████████████████| 2.87G/2.87G [02:13<00:00, 23.1MiB/s]
2023-02-08 16:16:18 [2023-02-09 00:16:18 +0000] [7] [INFO] Started server process [7]
2023-02-08 16:16:18 [2023-02-09 00:16:18 +0000] [7] [INFO] Waiting for application startup.
2023-02-08 16:16:18 [2023-02-09 00:16:18 +0000] [7] [INFO] Application startup complete.
2023-02-08 16:17:21 [2023-02-09 00:17:21 +0000] [7] [ERROR] Exception in ASGI application
2023-02-08 16:17:21 Traceback (most recent call last):
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2023-02-08 16:17:21     result = await app(  # type: ignore[func-returns-value]
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-02-08 16:17:21     return await self.app(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
2023-02-08 16:17:21     await super().__call__(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-02-08 16:17:21     await self.middleware_stack(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-02-08 16:17:21     raise exc
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-02-08 16:17:21     await self.app(scope, receive, _send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2023-02-08 16:17:21     raise exc
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2023-02-08 16:17:21     await self.app(scope, receive, sender)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-02-08 16:17:21     raise e
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-02-08 16:17:21     await self.app(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
2023-02-08 16:17:21     await route.handle(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
2023-02-08 16:17:21     await self.app(scope, receive, send)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-02-08 16:17:21     response = await func(request)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2023-02-08 16:17:21     raw_response = await run_endpoint_function(
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2023-02-08 16:17:21     return await run_in_threadpool(dependant.call, **values)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-02-08 16:17:21     return await anyio.to_thread.run_sync(func, *args)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-02-08 16:17:21     return await get_asynclib().run_sync_in_worker_thread(
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-02-08 16:17:21     return await future
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-02-08 16:17:21     result = context.run(func, *args)
2023-02-08 16:17:21   File "/app/app/webservice.py", line 71, in transcribe
2023-02-08 16:17:21     result = run_asr(audio_file.file, task, language, initial_prompt)
2023-02-08 16:17:21   File "/app/app/webservice.py", line 122, in run_asr
2023-02-08 16:17:21     result = model.transcribe(audio, **options_dict)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
2023-02-08 16:17:21     mel = log_mel_spectrogram(audio)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram
2023-02-08 16:17:21     stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
2023-02-08 16:17:21   File "/app/.venv/lib/python3.10/site-packages/torch/functional.py", line 630, in stft
2023-02-08 16:17:21     input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
2023-02-08 16:17:21 RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]
2023-02-08 16:18:29 [2023-02-09 00:18:29 +0000] [7] [ERROR] Exception in ASGI application
2023-02-08 16:18:29 Traceback (most recent call last):
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2023-02-08 16:18:29     result = await app(  # type: ignore[func-returns-value]
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-02-08 16:18:29     return await self.app(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
2023-02-08 16:18:29     await super().__call__(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-02-08 16:18:29     await self.middleware_stack(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-02-08 16:18:29     raise exc
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-02-08 16:18:29     await self.app(scope, receive, _send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2023-02-08 16:18:29     raise exc
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2023-02-08 16:18:29     await self.app(scope, receive, sender)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-02-08 16:18:29     raise e
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-02-08 16:18:29     await self.app(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
2023-02-08 16:18:29     await route.handle(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
2023-02-08 16:18:29     await self.app(scope, receive, send)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-02-08 16:18:29     response = await func(request)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2023-02-08 16:18:29     raw_response = await run_endpoint_function(
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2023-02-08 16:18:29     return await run_in_threadpool(dependant.call, **values)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-02-08 16:18:29     return await anyio.to_thread.run_sync(func, *args)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-02-08 16:18:29     return await get_asynclib().run_sync_in_worker_thread(
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-02-08 16:18:29     return await future
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-02-08 16:18:29     result = context.run(func, *args)
2023-02-08 16:18:29   File "/app/app/webservice.py", line 71, in transcribe
2023-02-08 16:18:29     result = run_asr(audio_file.file, task, language, initial_prompt)
2023-02-08 16:18:29   File "/app/app/webservice.py", line 122, in run_asr
2023-02-08 16:18:29     result = model.transcribe(audio, **options_dict)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
2023-02-08 16:18:29     mel = log_mel_spectrogram(audio)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram
2023-02-08 16:18:29     stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
2023-02-08 16:18:29   File "/app/.venv/lib/python3.10/site-packages/torch/functional.py", line 630, in stft
2023-02-08 16:18:29     input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
2023-02-08 16:18:29 RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]
2023-02-08 16:19:21 [2023-02-09 00:19:21 +0000] [7] [ERROR] Exception in ASGI application
2023-02-08 16:19:21 Traceback (most recent call last):
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2023-02-08 16:19:21     result = await app(  # type: ignore[func-returns-value]
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-02-08 16:19:21     return await self.app(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
2023-02-08 16:19:21     await super().__call__(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-02-08 16:19:21     await self.middleware_stack(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-02-08 16:19:21     raise exc
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-02-08 16:19:21     await self.app(scope, receive, _send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2023-02-08 16:19:21     raise exc
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2023-02-08 16:19:21     await self.app(scope, receive, sender)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-02-08 16:19:21     raise e
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-02-08 16:19:21     await self.app(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
2023-02-08 16:19:21     await route.handle(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
2023-02-08 16:19:21     await self.app(scope, receive, send)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-02-08 16:19:21     response = await func(request)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2023-02-08 16:19:21     raw_response = await run_endpoint_function(
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2023-02-08 16:19:21     return await run_in_threadpool(dependant.call, **values)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-02-08 16:19:21     return await anyio.to_thread.run_sync(func, *args)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-02-08 16:19:21     return await get_asynclib().run_sync_in_worker_thread(
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-02-08 16:19:21     return await future
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-02-08 16:19:21     result = context.run(func, *args)
2023-02-08 16:19:21   File "/app/app/webservice.py", line 71, in transcribe
2023-02-08 16:19:21     result = run_asr(audio_file.file, task, language, initial_prompt)
2023-02-08 16:19:21   File "/app/app/webservice.py", line 122, in run_asr
2023-02-08 16:19:21     result = model.transcribe(audio, **options_dict)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
2023-02-08 16:19:21     mel = log_mel_spectrogram(audio)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram
2023-02-08 16:19:21     stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)
2023-02-08 16:19:21   File "/app/.venv/lib/python3.10/site-packages/torch/functional.py", line 630, in stft
2023-02-08 16:19:21     input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
2023-02-08 16:19:21 RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]
2023-02-08 23:06:56 [2023-02-09 07:06:56 +0000] [1] [INFO] Starting gunicorn 20.1.0
2023-02-08 23:06:56 [2023-02-09 07:06:56 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
2023-02-08 23:06:56 [2023-02-09 07:06:56 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-02-08 23:06:56 [2023-02-09 07:06:56 +0000] [7] [INFO] Booting worker with pid: 7
2023-02-08 23:07:12 [2023-02-09 07:07:12 +0000] [7] [INFO] Started server process [7]
2023-02-08 23:07:12 [2023-02-09 07:07:12 +0000] [7] [INFO] Waiting for application startup.
2023-02-08 23:07:12 [2023-02-09 07:07:12 +0000] [7] [INFO] Application startup complete.
```

**Comment by blundercode** [comment]
Is your docker configured to run both GPUs at the same time?
