### ISSUE TITLE
upload fileName with non-ASCII char. will cause error

### ISSUE THREAD

**Issue by andythebreaker** [ahmetoner/whisper-asr-webservice#91]
- using docker
- tested on both `http://127.0.0.1:8888/docs#/Endpoints/transcribe_asr_post` and `curl` (via bash/cmd)

if i input a file name (with non-ascii char. )e.g.:`2023 04 11 AKB48 Team TP UNIT P．王逸嘉「浪Live」直播 [IL4cV9TMDy8].mp4.mp3`

it will transcribe fine but can't give result via http. (ERR MSG @ the END)

it is caused by line 87 of `/app/webservice.py` which is :

```
return StreamingResponse(myFile, media_type="text/plain", 
                            headers={'Content-Disposition': f'attachment; filename="{filename}.{output}"'})
```

and if i change file name to ENGLISH, it wil be ok (NO ERROR).

---

ERR MSG:
```
[2023-04-11 17:44:54 +0000] [7] [INFO] Application startup complete.

[2023-04-11 17:48:44 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 22-42: ordinal not in range(256)

[2023-04-11 17:50:26 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 22-42: ordinal not in range(256)

[2023-04-11 17:51:26 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 22-42: ordinal not in range(256)

[2023-04-12 12:58:00 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 71, in transcribe

    result = run_asr(audio_file.file, task, language, initial_prompt)

  File "/app/app/webservice.py", line 122, in run_asr

    result = model.transcribe(audio, **options_dict)

  File "/app/.venv/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe

    mel = log_mel_spectrogram(audio)

  File "/app/.venv/lib/python3.10/site-packages/whisper/audio.py", line 115, in log_mel_spectrogram

    stft = torch.stft(audio, N_FFT, HOP_LENGTH, window=window, return_complex=True)

  File "/app/.venv/lib/python3.10/site-packages/torch/functional.py", line 630, in stft

    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)

RuntimeError: 2D or 3D (batch mode) tensor expected for input, but got: [ torch.FloatTensor{1,1,0} ]

[2023-04-12 13:32:22 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 22-28: ordinal not in range(256)

[2023-04-15 14:47:17 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 53-58: ordinal not in range(256)

[2023-04-15 15:08:39 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 53-58: ordinal not in range(256)

[2023-04-15 15:33:29 +0000] [7] [ERROR] Exception in ASGI application

Traceback (most recent call last):

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__

    raise exc

  File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__

    await self.app(scope, receive, sender)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__

    await route.handle(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle

    await self.app(scope, receive, send)

  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app

    response = await func(request)

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app

    raw_response = await run_endpoint_function(

  File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/app/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/app/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/app/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/app/app/webservice.py", line 87, in transcribe

    return StreamingResponse(myFile, media_type="text/plain",

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 242, in __init__

    self.init_headers(headers)

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 72, in init_headers

    raw_headers = [

  File "/app/.venv/lib/python3.10/site-packages/starlette/responses.py", line 73, in <listcomp>

    (k.lower().encode("latin-1"), v.encode("latin-1"))

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 53-58: ordinal not in range(256)

```

**Comment by zj1123581321** [comment]
I'm having the same problem :)
